Library Updates
Crab-Robotics/Crabot pull request #30
Opened 2020-11-08 22:21 UTC by gallifreyancat

Added reverse gyro drive and color sensors to CrabRobotLibrary.  Added movement to KateSkillLibrary.

2020-11-11 21:51 UTC, codefeld reviewed
Nice job adding the color sensors! I saw that you added a reverse gyro drive function. We already have one called "bw_gyro_drive" that we are using. I would suggest taking out the one you added because having two reverse gyro drive functions may become confusing for some people.

2020-11-14 16:25 UTC, codefeld commented on CrabRobotLibrary.py
> +	color_sensor_right = ColorSensor(Port.S4)
It looks like Zac added these same lines, so there is a conflict that needs to be resolved.

2020-12-14 22:28 UTC, HipsterDave approved these changes

2020-12-14 22:29 UTC, HipsterDave requested changes
Hmm... seems like this PR is conflicting with the master branch. If it is an outdated branch, I can help you bring it up to date!

2020-12-19 19:42 UTC, closed without merging

2020-12-19 19:42 UTC, gallifreyancat commented
Closed