Created run_cube.py
Crab-Robotics/Crabot pull request #57
Opened 2020-12-19 22:27 UTC by Blastoff88

2020-12-20 17:21 UTC, codefeld requested changes
This got further than before, but I'm still not able to run it completely.

2020-12-20 17:21 UTC, codefeld commented on run_cube.py
> +	crabot.gyro_reset()
Before resetting the gyro, we should make the robot drive backward so that we can ensure it is completely backed up against the wall/jig.

2020-12-20 17:21 UTC, codefeld commented on run_cube.py
> +    crabot.front_activate(10000, 11440, Direction.CLOCKWISE)
On our robot, the motor stalls here.

2021-01-03 16:56 UTC, codefeld requested changes
Can you post some information on where to start the robot for this program?

2021-01-03 16:56 UTC, codefeld commented on run_cube.py
> +	run_table_2(crabot)
I don't think this is a function in this file.
```suggestion
```

2021-01-23 00:47 UTC, closed without merging

2021-01-23 00:48 UTC, Blastoff88 commented
I decided to close it and open a new one without run_basketball.