To-Do 1/24/2021
Crab-Robotics/Crabot pull request #77
Opened 2021-01-25 19:54 UTC by HipsterDave

2021-01-27 00:46 UTC, gallifreyancat approved these changes

2021-01-27 01:01 UTC, jkutner approved these changes

2021-01-29 02:41 UTC, codefeld requested changes
Hmm

2021-01-29 02:41 UTC, codefeld commented on todo.md
> + - [ ] Build het innovation project model - _Richard_
```suggestion
 - [ ] Build the innovation project model - _Richard_
```

2021-01-29 02:42 UTC, codefeld approved these changes

2021-01-29 02:42 UTC, merged